ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}
USER 0
RUN rm -rf /bindata
LABEL org.opencontainers.image.revision="a5588da21699fccce921cb1d4ac5894f47889399"
LABEL org.opencontainers.image.source="https://github.com/k8snetworkplumbingwg/sriov-network-operator"
COPY webhook /usr/bin/webhook
USER 1001
CMD ["/usr/bin/webhook"]

ARG PATCH_SHA256
LABEL mock-smartnic.patch-sha256="${PATCH_SHA256}"
